[db]
user = "musicbrainz"
password = "musicbrainz"
host = "localhost"
port = 5432
name = "musicbrainz"

[meili]
url = "http://localhost:7700"
api_key = "masterKey123"

[api]
port = 3000

[sync]
artist_batch_size = 10_000
album_batch_size = 5_000
