[package]
name = "mbmeta-pipeline"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
anyhow.workspace = true
sqlx.workspace = true
mbmeta-db.workspace = true
mbmeta-meili.workspace = true
mbmeta-model.workspace = true
tracing.workspace = true
