[package]
name = "metadada-pipeline"
version = "0.1.0"
edition = "2024"

[dependencies]
futures.workspace = true
anyhow.workspace = true
sqlx.workspace = true
metadada-db.workspace = true
metadada-meili.workspace = true
tracing.workspace = true
indicatif.workspace = true
